/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AthsrueasEthRouteImport } from './routes/athsrueas-eth'
import { Route as CvRouteImport } from './routes/cv'
import { Route as HostedBlogPagesSlugRouteImport } from './routes/hosted-blog-pages/$slug'
import { Route as ProjectsDephiRouteImport } from './routes/projects/dephi'
import { Route as Web3DephiRouteImport } from './routes/web3/dephi'
import { Route as WritingIndexRouteImport } from './routes/writing/index'
import { Route as WritingSlugRouteImport } from './routes/writing/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthsrueasEthRoute = AthsrueasEthRouteImport.update({
  id: '/athsrueas-eth',
  path: '/athsrueas-eth',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedBlogPagesSlugRoute = HostedBlogPagesSlugRouteImport.update({
  id: '/hosted-blog-pages/$slug',
  path: '/hosted-blog-pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsDephiRoute = ProjectsDephiRouteImport.update({
  id: '/projects/dephi',
  path: '/projects/dephi',
  getParentRoute: () => rootRouteImport,
} as any)
const Web3DephiRoute = Web3DephiRouteImport.update({
  id: '/web3/dephi',
  path: '/web3/dephi',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/writing/$slug',
  path: '/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/athsrueas-eth': typeof AthsrueasEthRoute
  '/cv': typeof CvRoute
  '/hosted-blog-pages/$slug': typeof HostedBlogPagesSlugRoute
  '/projects/dephi': typeof ProjectsDephiRoute
  '/web3/dephi': typeof Web3DephiRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/athsrueas-eth': typeof AthsrueasEthRoute
  '/cv': typeof CvRoute
  '/hosted-blog-pages/$slug': typeof HostedBlogPagesSlugRoute
  '/projects/dephi': typeof ProjectsDephiRoute
  '/web3/dephi': typeof Web3DephiRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing': typeof WritingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/athsrueas-eth': typeof AthsrueasEthRoute
  '/cv': typeof CvRoute
  '/hosted-blog-pages/$slug': typeof HostedBlogPagesSlugRoute
  '/projects/dephi': typeof ProjectsDephiRoute
  '/web3/dephi': typeof Web3DephiRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/athsrueas-eth'
    | '/cv'
    | '/hosted-blog-pages/$slug'
    | '/projects/dephi'
    | '/web3/dephi'
    | '/writing/$slug'
    | '/writing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/athsrueas-eth'
    | '/cv'
    | '/hosted-blog-pages/$slug'
    | '/projects/dephi'
    | '/web3/dephi'
    | '/writing/$slug'
    | '/writing'
  id:
    | '__root__'
    | '/'
    | '/athsrueas-eth'
    | '/cv'
    | '/hosted-blog-pages/$slug'
    | '/projects/dephi'
    | '/web3/dephi'
    | '/writing/$slug'
    | '/writing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AthsrueasEthRoute: typeof AthsrueasEthRoute
  CvRoute: typeof CvRoute
  HostedBlogPagesSlugRoute: typeof HostedBlogPagesSlugRoute
  ProjectsDephiRoute: typeof ProjectsDephiRoute
  Web3DephiRoute: typeof Web3DephiRoute
  WritingSlugRoute: typeof WritingSlugRoute
  WritingIndexRoute: typeof WritingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athsrueas-eth': {
      id: '/athsrueas-eth'
      path: '/athsrueas-eth'
      fullPath: '/athsrueas-eth'
      preLoaderRoute: typeof AthsrueasEthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted-blog-pages/$slug': {
      id: '/hosted-blog-pages/$slug'
      path: '/hosted-blog-pages/$slug'
      fullPath: '/hosted-blog-pages/$slug'
      preLoaderRoute: typeof HostedBlogPagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/dephi': {
      id: '/projects/dephi'
      path: '/projects/dephi'
      fullPath: '/projects/dephi'
      preLoaderRoute: typeof ProjectsDephiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web3/dephi': {
      id: '/web3/dephi'
      path: '/web3/dephi'
      fullPath: '/web3/dephi'
      preLoaderRoute: typeof Web3DephiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AthsrueasEthRoute: AthsrueasEthRoute,
  CvRoute: CvRoute,
  HostedBlogPagesSlugRoute: HostedBlogPagesSlugRoute,
  ProjectsDephiRoute: ProjectsDephiRoute,
  Web3DephiRoute: Web3DephiRoute,
  WritingSlugRoute: WritingSlugRoute,
  WritingIndexRoute: WritingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
